name: Release Creation

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create Zip Package
        run: zip -r module.zip module.json crawl.js README.md -x "*.git*"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            module.json
            module.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
