name: Release Creation

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create Module Zip
        run: zip -r ./module.zip module.json crawl.js

      - name: Create or Update Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            module.json
            module.zip